### ISSUE TITLE
Mod content mismatch

### ISSUE THREAD

**Issue by ikiris** [Wyrrrd/IndustrialDisplayPlates#11]
Getting a mod content mismatch on a server  (Space Exploration + kastorio)

and this has no visible settings, so i suspect there's some issue with the mod doing dynamic loading of content or something as described by the error message.

**Comment by ikiris** [comment]
Looks like it might be specifically the new 18.3

**Comment by Wyrrrd** [comment]
I messed up the versions. You have the fixed one, I assume the server automatically downloaded the false one and now is not updating, since there is no newer version. Please ask the maintainer of the server to manually redownload the mod (0.18.3), this should fix it. Sorry.

**Comment by ikiris** [comment]
You need to just bump the version number. Factorio can't handle a release
without version change.

Theres also no way to contact owners of a public server unless you can join said server.

**Comment by Wyrrrd** [comment]
Fixed in [0.18.5](https://github.com/Wyrrrd/IndustrialDisplayPlates/releases/tag/v0.18.5)
