### ISSUE TITLE
Hover Text above display plates with item name

### ISSUE THREAD

**Issue by billbo99** [Wyrrrd/IndustrialDisplayPlates#12]
Any chance the plates could have some "floating text" appear when a players cursor hovers over them as some icons are very hard to tell from one another ?

**Comment by Wyrrrd** [comment]
Do you have any other mod in mind doing that already, so I might get some inspiration about how to do this?

**Comment by Wyrrrd** [comment]
Closing for now, because I see no way this can be even accomplished with a mod. If you find something similar in another mod, feel free to reopen this issue.
