### ISSUE TITLE
Light display mode / additional materials

### ISSUE THREAD

**Issue by Wyrrrd** [Wyrrrd/IndustrialDisplayPlates#13]
Needs graphics rework, something along the lines of a multi-layer approach.

+ one layer would be the base material colour (maybe even extracted from the base material plate)
+ one would be the border texture (polished, like the steel plate, or rusty/dirty like the iron one)
+ one would be the (dynamically loaded) light or dark display area, based on the state of a GUI checkbox or similar

**Comment by billbo99** [comment]
Did deadlock give you the source blender graphics files?

**Comment by Wyrrrd** [comment]
No, but since I intend to use the original textures, just programmatically changed in hue/contrast/brightness, this should be fine. I manually separated the border from the display area already, even created a light variant, that's no problem.

The actual limiting factor right now is the logic. IDP assumes a maximum of one sprite attached to each entity, the icon, and therefore handles all sprites as icons. No chance of just adding extra sprites without having to tweak a lot of the other code, and I can't find the time to think of a working solution.

If someone wants to play around with the images while I am busy being busy, just ask :)

**Comment by Wyrrrd** [comment]
Wontfix, see [README.md](https://github.com/Wyrrrd/IndustrialDisplayPlates-Archive#readme) (sorry).

If you won't, I will forward the ideas to the new fork though.
