### ISSUE TITLE
Copy/Paste/Blueprint does not restore symbols

### ISSUE THREAD

**Issue by DeadlyDad** [Wyrrrd/IndustrialDisplayPlates#21]
I want to use it to label my bus so I can quickly tap whatever components I need without squinting--I use undergrounds for the UPS buff so seeing what is on each belt is a hassle. Labelling the belt from end-to-end pretty much _requires_ being able to copy/paste/blueprint the sets of plates, which is currently not working.  This bug was reported well over a year ago.   **PLEASE** fix it.

**Comment by Wyrrrd** [comment]
Wontfix, see [README.md](https://github.com/Wyrrrd/IndustrialDisplayPlates-Archive#readme) (sorry).
